version: "3"
services:
  registry:
    image: 'registry:2'
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ${REGISTRY_STORE_PATH:-"./src"}:/var/lib/registry
      - ./cfg/auth:/auth
    networks:
      - default
  drone:
    image: drone/drone
    ports:
      - "1285:80"
    volumes:
      - ./cfg/drone:/data
    env_file: .env
    networks:
      - default
  drone-runner:
    image: drone/drone-runner-docker
    ports:
      - 5001:3000
    env_file: .env
    environment:
      - "DRONE_RPC_HOST=drone"
      - "DRONE_RPC_PROTO=http"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json
    networks:
      - default
  cleaner:
    image: anoxis/registry-cli
    env_file: .env
    entrypoint: "/bin/sh -c 'while :; do eval /registry.py -r http://registry:5000 -l ${REGISTRY_USER}:${REGISTRY_PASSWORD} --delete --num ${KEEP_VERSIONS:-5} && sleep ${CLEAN_TIME:-6h}; echo ${KEEP_VERSIONS}; done'"
    networks:
      - default
    depends_on:
      - registry
networks:
  default:
